name: Build Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: python-package
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build
      
      - name: Install Cloudsmith CLI        
        run: |
          curl -sSL https://dl.cloudsmith.io/public/cloudsmith/client/gpg.key | sudo apt-key add -
          curl -sSL https://dl.cloudsmith.io/public/cloudsmith/client/debian.deb.txt | sudo tee /etc/apt/sources.list.d/cloudsmith-client.list
          sudo apt-get update
          sudo apt-get install -y cloudsmith-cli

      - name: Publish package to Cloudsmith 
        run: cloudsmith push python your_namespace/staging dist/*.tar.gz --republish
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/
          if-no-files-found: error
          retention-days: 5
