name: Build Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: python-package
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build
      
      - name: Install Cloudsmith CLI        
        run: |
          # download latest release and make it executable
          curl -s https://api.github.com/repos/cloudsmith-io/cloudsmith-cli/releases/latest | sed -n 's/"browser_download_url": //p' | xargs wget -qO cloudsmith.pyz
          chmod +x ./cloudsmith.pyz
          #  move it into your $PATH
          sudo mv ./cloudsmith.pyz /usr/local/bin/cloudsmith

      - name: Publish package to Cloudsmith 
        run: 
          cloudsmith push python interview-aishwaryaditya-jha/staging dist/*.tar.gz --republish
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/
          if-no-files-found: error
          retention-days: 5
